name: Terraform Workflow
on:
  workflow_dispatch:
  # push:
  #    branches:
  #      - master  

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: |
          cd EKS
          terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Plan
        run: |
            cd EKS
             terraform plan -var access_key="${{ secrets.AWS_ACCESS_KEY_ID }}" -var secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only apply changes on main branch push
        run: | 
          cd EKS
          terraform apply -var access_key="${{ secrets.AWS_ACCESS_KEY_ID }}" -var secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" --auto-approve
        # env:
          # TF_INPUT: false  # Disable interactive mode
          # TF_IN_AUTOMATION: true  # Set Terraform to automation mode
      # - name: Terraform destroy
      #   # if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only apply changes on main branch push
      #   run: | 
      #     cd EKS
      #     terraform destroy -var access_key="${{ secrets.AWS_ACCESS_KEY_ID }}" -var secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" --auto-approve
