name: javaapp deployment
on:
  workflow_call:
jobs:
  deployment:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
        
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: GKprojects/deployment   # Replace with the repository URL
          ref: main 
          token: ${{secrets.PAT_TOKEN }}
   
      - name: Modify Manifest
        run: |
              # Replace the image and tag in the manifest file
               echo "GitHub SHA: ${{ github.run_number }}"
               sed -i "s|${{ secrets.DOCKER_REPO }}:.*|${{ secrets.DOCKER_REPO }}:${{ github.run_number }}|" deployment.yaml
     
      - name: Debug - Show Git Status After Changes
        run: git status
        shell: bash
   
  
      - name: Commit and Push Change
        run: |
              git config --global user.name "GKprojects"
              git config --global user.email "ponngokul98@gmail.com"
              git add deployment.yaml
              git commit -m "Update image with ${{ github.run_number }}"
              git push
        env:
            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
