name: MAIN_PIPELINE
on:
  workflow_dispatch:
  push:
    branches:
      - qa
      - dev
      - main
  pull_request:
      branches:
        - dev     
permissions:
    checks: write
    security-events: write
    packages: write
    actions: write
    pull-requests: write
    contents: read
    
jobs:
    Talisman:
      name: Talisman
      uses: prem1903/ekscluster/.github/workflows/talisman.yml@main
      secrets: inherit
      #octo-org/example-repo/.github/workflows/reusable-workflow.yml@main

    Sbom:
      name: Sbom
      uses: prem1903/ekscluster/.github/workflows/sbom.yml@main
      secrets: inherit

    KICS:
      needs: Talisman
      name: KICS
      uses: prem1903/ekscluster/.github/workflows/KICS.yml@main
      secrets: inherit 
    
    Unit_Test:
      needs: [ Sbom, Talisman ]
      name: Unit Test
      uses: prem1903/ekscluster/.github/workflows/UnitTest.yaml@main
      secrets: inherit

    Build_Test:
      needs: KICS
      name: Build and Test
      uses: prem1903/ekscluster/.github/workflows/build.yaml@main
      secrets: inherit

    Docker_build:
      needs: Sbom
      name: Docker build
      uses: prem1903/ekscluster/.github/workflows/docker.yml@main
      secrets: inherit
      
    Deployment:
      needs: Docker_build
      name: Deployment
      uses: prem1903/ekscluster/.github/workflows/deploy.yml@main
      secrets: inherit
      
    Deploy:
      runs-on: ubuntu-latest
      needs: Deployment 
      steps:
       - name: Install Kubectl
         uses: azure/setup-kubectl@v3
         with:
          version: 'v1.28.0' # default is latest stable
         id: install
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
       - name: Set kubectl context
         run: aws eks --region us-east-1 update-kubeconfig --name ekscluster
       - name: Checkout Repository
         uses: actions/checkout@v3
         with:
            repository: prem1903/deployment   
            token: ${{ secrets.PAT_TOKEN }}
       - name: Apply Kubernetes manifests
         run: |
          # cd deployment
          kubectl apply -f deployment.yaml -f service.yaml
